import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import {
  AlertTriangle, Archive, BarChart3, Building2, CalendarDays, CheckCircle2,
  ChevronLeft, ChevronRight, CircleHelp, Copy, Download, Eye, EyeOff,
  FileBarChart, LayoutDashboard, LogOut, Menu, MoreHorizontal, Pencil, Plus,
  Search, Settings2, ShieldCheck, Trash2, UserPlus, Users, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import patoverLogo from "@/assets/patover-logo.png.asset.json";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "PATOVER | Gestión de eventos ULS" },
    { name: "description", content: "Mockup funcional de gestión universitaria para organizaciones, eventos y reportes." },
    { property: "og:title", content: "PATOVER | Gestión de eventos ULS" },
    { property: "og:description", content: "Plataforma de gestión de eventos y actividades universitarias." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: Index,
});

type View = "dashboard" | "organizaciones" | "eventos" | "reportes" | "perfil";
type Account = { name: string; initials: string; role: string; email: string; password: string };
type EventStatus = "Publicado" | "Configurado" | "Borrador" | "Finalizado" | "Archivado";
type Organization = { name: string; initials: string; contact: string; email: string; status: "Activa" | "Inactiva"; events: number };
type PatoverEvent = { name: string; org: string; date: string; place: string; registered: number; capacity: number; status: EventStatus };

const initialOrganizations: Organization[] = [
  { name: "Facultad de Ingeniería", initials: "FI", contact: "Camila Soto", email: "eventos.fi@userena.cl", status: "Activa", events: 8 },
  { name: "Facultad de Humanidades", initials: "FH", contact: "Diego Rojas", email: "humanidades@userena.cl", status: "Activa", events: 5 },
  { name: "Dirección de Vinculación", initials: "DV", contact: "María Paz Leiva", email: "vinculacion@userena.cl", status: "Activa", events: 12 },
  { name: "Centro de Estudiantes", initials: "CE", contact: "Tomás Vega", email: "centro.estudiantes@userena.cl", status: "Inactiva", events: 2 },
];

const initialEvents: PatoverEvent[] = [
  { name: "Feria de Innovación ULS 2026", org: "Facultad de Ingeniería", date: "24 sep 2026", place: "Campus Ignacio Domeyko", registered: 428, capacity: 500, status: "Publicado" },
  { name: "Encuentro de Humanidades", org: "Facultad de Humanidades", date: "02 oct 2026", place: "Salón Pentágono", registered: 186, capacity: 240, status: "Configurado" },
  { name: "Seminario Vinculación Regional", org: "Dirección de Vinculación", date: "18 oct 2026", place: "Aula Magna", registered: 94, capacity: 300, status: "Borrador" },
  { name: "Congreso de Investigación 2026", org: "Vicerrectoría de Investigación", date: "30 ago 2026", place: "Campus Andrés Bello", registered: 310, capacity: 350, status: "Finalizado" },
];

function Index() {
  const [signedIn, setSignedIn] = useState(false);
  const [account, setAccount] = useState<Account>({ name: "Flavio Cortés", initials: "FC", role: "Administrador global", email: "demo@userena.cl", password: "demo1234" });
  if (!signedIn) return <Login account={account} onLogin={() => setSignedIn(true)} />;
  return <Workspace account={account} setAccount={setAccount} onLogout={() => setSignedIn(false)} />;
}

function Login({ account, onLogin }: { account: Account; onLogin: () => void }) {
  const [recover, setRecover] = useState(false);
  const [sent, setSent] = useState(false);
  const [error, setError] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [message, setMessage] = useState("");
  const [errorText, setErrorText] = useState("");
  const submit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const email = String(form.get("email") ?? "").trim();
    const password = String(form.get("password") ?? "");
    if (!email || (!recover && !password)) { setError(true); setErrorText("Completa los campos obligatorios para continuar."); return; }
    if (recover) { setSent(true); return; }
    if (email.toLowerCase() !== account.email.toLowerCase() || password !== account.password) {
      setError(true); setErrorText("Correo o contraseña incorrectos."); return;
    }
    onLogin();
  };
  return <main className="login-shell">
    <section className="login-brand"><BrandMark large /><div><p className="brand-kicker">Universidad de La Serena</p><h1>Gestión universitaria, en un solo lugar.</h1><p>Organiza eventos, coordina equipos y toma decisiones con información confiable.</p></div><p className="login-foot">Plataforma institucional · Acceso seguro</p></section>
    <section className="login-panel"><form className="auth-form" onSubmit={submit}>
      <div className="auth-icon"><ShieldCheck /></div><p className="eyebrow">PATOVER</p><h2>{recover ? "Recuperar contraseña" : "Inicia sesión en tu cuenta"}</h2>
      <p className="supporting">{recover ? "Ingresa tu correo institucional y te enviaremos las instrucciones." : "Accede con tus credenciales institucionales."}</p>
      {sent ? <div className="success-panel"><CheckCircle2 /><strong>Revisa tu correo</strong><span>Enviamos las instrucciones de recuperación.</span></div> : <>
        <label>Correo institucional<Input name="email" type="email" placeholder="nombre@userena.cl" onChange={() => setError(false)} /></label>
        {!recover && <label>Contraseña<div className="password-field"><Input name="password" type={showPassword ? "text" : "password"} placeholder="••••••••" onChange={() => setError(false)} /><Button type="button" variant="ghost" size="icon" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? "Ocultar contraseña" : "Mostrar contraseña"}>{showPassword ? <EyeOff /> : <Eye />}</Button></div></label>}
        {error && <div className="inline-alert danger"><AlertTriangle /><span>{errorText}</span></div>}
        {!recover && <label className="check-row"><input type="checkbox" /> Recordarme</label>}
        <Button className="w-full" size="lg" type="submit">{recover ? "Enviar instrucciones" : "Iniciar sesión"}</Button>
        {!recover && <><div className="divider"><span>o continúa con</span></div><Button type="button" variant="outline" onClick={() => setMessage("Acceso con Google simulado")} className="w-full">G&nbsp;&nbsp; Iniciar sesión con Google</Button></>}
      </>}
      <Button type="button" variant="link" onClick={() => { setRecover(!recover); setSent(false); setError(false); }}>{recover ? "Volver al inicio de sesión" : "¿Olvidaste tu contraseña?"}</Button>
      {!recover && <p className="demo-note">Acceso actual: {account.email} / {account.password}. Puedes cambiarlo en Mi perfil.</p>}
      {message && <p className="form-message">{message}</p>}
    </form></section>
  </main>;
}

function BrandMark({ large = false }: { large?: boolean }) { return <div className={`brand-mark ${large ? "brand-mark-large" : ""}`}><img src={patoverLogo.url} alt="PATOVER" /></div>; }

function Workspace({ account, setAccount, onLogout }: { account: Account; setAccount: (a: Account) => void; onLogout: () => void }) {
  const [view, setView] = useState<View>("dashboard");
  const [mobileNav, setMobileNav] = useState(false);
  const [notice, setNotice] = useState("");
  const [orgs, setOrgs] = useState(initialOrganizations);
  const [events, setEvents] = useState(initialEvents);
  const titles: Record<View, string> = { dashboard: "Resumen general", organizaciones: "Organizaciones", eventos: "Eventos", reportes: "Reportes e indicadores", perfil: "Mi perfil" };
  const navigate = (next: View) => { setView(next); setMobileNav(false); };
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); };
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? "sidebar-open" : ""}`}><div className="sidebar-top"><BrandMark /><Button variant="ghost" size="icon" className="mobile-close" onClick={() => setMobileNav(false)} aria-label="Cerrar menú"><X /></Button></div><nav aria-label="Módulos principales">
      <NavItem icon={<LayoutDashboard />} label="Resumen" active={view === "dashboard"} onClick={() => navigate("dashboard")} /><p className="nav-label">Administración</p>
      <NavItem icon={<Building2 />} label="Organizaciones" active={view === "organizaciones"} onClick={() => navigate("organizaciones")} /><NavItem icon={<CalendarDays />} label="Eventos" active={view === "eventos"} onClick={() => navigate("eventos")} /><p className="nav-label">Análisis</p>
      <NavItem icon={<FileBarChart />} label="Reportes" active={view === "reportes"} onClick={() => navigate("reportes")} /><p className="nav-label">Cuenta</p>
      <NavItem icon={<ShieldCheck />} label="Mi perfil" active={view === "perfil"} onClick={() => navigate("perfil")} />
    </nav><div className="sidebar-bottom"><NavItem icon={<CircleHelp />} label="Ayuda" onClick={() => notify("Centro de ayuda disponible en la versión final")} /><NavItem icon={<LogOut />} label="Cerrar sesión" onClick={onLogout} /></div></aside>
    {mobileNav && <div className="nav-scrim" onClick={() => setMobileNav(false)} />}
    <div className="main-area"><header className="topbar"><div className="topbar-title"><Button variant="ghost" size="icon" className="menu-button" onClick={() => setMobileNav(true)} aria-label="Abrir menú"><Menu /></Button><div><p>PATOVER / {titles[view]}</p><h1>{titles[view]}</h1></div></div><div className="user-area"><Button variant="ghost" size="icon" aria-label="Configuración" onClick={() => navigate("perfil")}><Settings2 /></Button><button type="button" className="user-chip" onClick={() => navigate("perfil")} aria-label="Abrir mi perfil"><div className="avatar">{account.initials}</div><div className="user-copy"><strong>{account.name}</strong><span>{account.role}</span></div></button></div></header>
      <main className="workspace">{view === "dashboard" && <Dashboard navigate={navigate} events={events} orgCount={orgs.length} name={account.name.split(" ")[0]} />}{view === "organizaciones" && <Organizations organizations={orgs} setOrganizations={setOrgs} notify={notify} />}{view === "eventos" && <Events events={events} setEvents={setEvents} organizations={orgs} notify={notify} />}{view === "reportes" && <Reports events={events} notify={notify} />}{view === "perfil" && <Profile account={account} setAccount={setAccount} notify={notify} />}</main>
    </div>{notice && <div className="toast"><CheckCircle2 />{notice}</div>}
  </div>;
}

function NavItem({ icon, label, active, onClick }: { icon: React.ReactNode; label: string; active?: boolean; onClick?: () => void }) { return <Button variant="ghost" className={`nav-item ${active ? "active" : ""}`} onClick={onClick}>{icon}<span>{label}</span></Button>; }

function Dashboard({ navigate, events, orgCount, name }: { navigate: (view: View) => void; events: PatoverEvent[]; orgCount: number; name: string }) {
  return <div className="page-stack"><div className="page-intro"><div><p className="eyebrow">Miércoles, 16 de septiembre</p><h2>Buenas tardes, {name}</h2><p>Revisa la actividad reciente y los próximos hitos de la plataforma.</p></div><Button onClick={() => navigate("eventos")}><Plus /> Nuevo evento</Button></div>
    <div className="metric-grid"><Metric label="Eventos activos" value={String(events.filter(e => !["Finalizado", "Archivado"].includes(e.status)).length)} note="Estado actualizado" icon={<CalendarDays />} /><Metric label="Inscripciones" value="1.284" note="+18% este mes" icon={<Users />} /><Metric label="Organizaciones" value={String(orgCount)} note="Unidades registradas" icon={<Building2 />} /><Metric label="Asistencia media" value="78%" note="Últimos 30 días" icon={<BarChart3 />} /></div>
    <div className="dashboard-grid"><section className="panel"><div className="section-title"><div><p className="eyebrow">Próximamente</p><h3>Eventos en agenda</h3></div><Button variant="ghost" onClick={() => navigate("eventos")}>Ver todos <ChevronRight /></Button></div>{events.slice(0,3).map(event => <EventRow key={event.name} event={event} />)}</section><section className="panel"><div className="section-title"><div><p className="eyebrow">Actividad</p><h3>Inscripciones esta semana</h3></div></div><div className="mini-chart">{[35,48,44,68,58,82,74].map((h,i) => <div key={i}><span style={{ height: `${h}%` }} /><small>{["L","M","M","J","V","S","D"][i]}</small></div>)}</div><div className="chart-summary"><strong>326</strong><span>nuevas inscripciones</span></div></section></div>
  </div>;
}

function Metric({ label, value, note, icon }: { label: string; value: string; note: string; icon: React.ReactNode }) { return <article className="metric"><div className="metric-head"><span>{label}</span><div className="metric-icon">{icon}</div></div><strong>{value}</strong><p>{note}</p></article>; }

function Organizations({ organizations, setOrganizations, notify }: { organizations: Organization[]; setOrganizations: React.Dispatch<React.SetStateAction<Organization[]>>; notify: (message: string) => void }) {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState(0); const [editor, setEditor] = useState<"new" | "edit" | null>(null); const [usersOpen, setUsersOpen] = useState(false); const [deactivate, setDeactivate] = useState(false); const [detailOpen, setDetailOpen] = useState(false); const [addUser, setAddUser] = useState(false);
  const filtered = organizations.filter(o => `${o.name} ${o.initials}`.toLowerCase().includes(query.toLowerCase()));
  const current = organizations[selected];
  const saveOrganization = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const next: Organization = { name: String(form.get("name")), initials: String(form.get("initials")).toUpperCase(), contact: String(form.get("contact")), email: String(form.get("email")), status: "Activa", events: editor === "edit" ? current?.events ?? 0 : 0 }; if (editor === "new") { setOrganizations(prev => [...prev, next]); setSelected(organizations.length); } else setOrganizations(prev => prev.map((item, i) => i === selected ? { ...next, status: item.status } : item)); setEditor(null); notify(editor === "new" ? "Organización creada correctamente" : "Organización actualizada correctamente"); };
  return <div className="page-stack"><div className="page-intro"><div><p className="eyebrow">MC-03</p><h2>Administración de organizaciones</h2><p>Gestiona las unidades organizadoras y sus responsables.</p></div><Button onClick={() => setEditor("new")}><Plus /> Nueva organización</Button></div>
    <section className="panel table-panel"><div className="toolbar"><div className="search-field"><Search /><Input aria-label="Buscar organizaciones" value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar organizaciones..." /></div><span className="result-count">{filtered.length} organizaciones</span></div>
      {filtered.length ? <div className="table-wrap"><table><thead><tr><th>Organización</th><th>Código</th><th>Responsable</th><th>Estado</th><th>Eventos</th><th></th></tr></thead><tbody>{filtered.map(org => { const realIndex = organizations.indexOf(org); return <tr key={org.initials} className={selected === realIndex ? "selected-row" : ""} onClick={() => setSelected(realIndex)}><td><div className="org-cell"><span className="org-avatar">{org.initials}</span><strong>{org.name}</strong></div></td><td>{org.initials}</td><td><strong>{org.contact}</strong><small>{org.email}</small></td><td><Status status={org.status} /></td><td>{org.events}</td><td><Button variant="ghost" size="icon" aria-label={`Seleccionar ${org.name}`} onClick={() => setSelected(realIndex)}><MoreHorizontal /></Button></td></tr>; })}</tbody></table></div> : <EmptyState title="No se encontraron organizaciones" text="Intenta con otros filtros o crea una nueva organización." />}
      <div className="table-footer"><span>Mostrando {filtered.length} de {organizations.length}</span><div><Button variant="outline" size="icon" disabled><ChevronLeft /></Button><Button variant="outline" size="icon" disabled><ChevronRight /></Button></div></div>
    </section>
    {current && <section className="detail-strip"><div className="org-avatar large">{current.initials}</div><div><p className="eyebrow">Organización seleccionada</p><h3>{current.name}</h3><p>{current.contact} · {current.events} eventos vinculados</p></div><div className="detail-actions"><Button variant="outline" onClick={() => setDetailOpen(true)}><Eye /> Ver detalle</Button><Button variant="outline" onClick={() => setEditor("edit")}><Pencil /> Editar</Button><Button variant="outline" onClick={() => setDeactivate(true)}>{current.status === "Activa" ? <Archive /> : <CheckCircle2 />}{current.status === "Activa" ? "Desactivar" : "Activar"}</Button><Button onClick={() => setUsersOpen(true)}><UserPlus /> Asociar usuarios</Button></div></section>}
    {editor && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">MC-03</p><h2>{editor === "new" ? "Nueva organización" : "Editar organización"}</h2></div><Button variant="ghost" size="icon" onClick={() => setEditor(null)} aria-label="Cerrar"><X /></Button></header><form onSubmit={saveOrganization}><div className="modal-body form-grid"><label className="span-2">Nombre de la organización *<Input name="name" required defaultValue={editor === "edit" ? current?.name : ""} /></label><label>Código *<Input name="initials" required maxLength={5} defaultValue={editor === "edit" ? current?.initials : ""} /></label><label>Estado<select disabled><option>Activa</option></select></label><label>Responsable *<Input name="contact" required defaultValue={editor === "edit" ? current?.contact : ""} /></label><label>Correo institucional *<Input name="email" type="email" required defaultValue={editor === "edit" ? current?.email : ""} /></label><label className="span-2">Descripción<textarea defaultValue="Unidad organizadora de actividades y eventos institucionales." /></label></div><footer><Button type="button" variant="outline" onClick={() => setEditor(null)}>Cancelar</Button><Button type="submit">Guardar cambios</Button></footer></form></section></div>}
    {detailOpen && current && <Modal wide title="Detalle de organización" onClose={() => setDetailOpen(false)} onSave={() => setDetailOpen(false)} saveLabel="Cerrar"><div className="entity-detail"><section className="entity-banner"><div className="org-avatar large">{current.initials}</div><div><h3>{current.name}</h3><p>Unidad organizadora de actividades y eventos institucionales.</p></div><Status status={current.status} /></section><section className="detail-facts"><div><span>Nombre</span><strong>{current.name}</strong></div><div><span>Código</span><strong>{current.initials}</strong></div><div><span>Estado</span><strong>{current.status}</strong></div><div><span>Fecha de creación</span><strong>12 marzo 2025</strong></div></section><section><div className="section-title"><div><p className="eyebrow">Miembros asociados</p><h3>Equipo y permisos</h3></div><Button onClick={() => { setDetailOpen(false); setUsersOpen(true); }}><UserPlus /> Administrar</Button></div>{[["Camila Soto","Dueño"],["María Rodríguez","Administrador"],["Juan Pérez","Editor"],["Carla Gómez","Lector"]].map(([name, role]) => <div className="member-row" key={name}><span className="avatar">{name.split(" ").map(v => v[0]).join("")}</span><div><strong>{name}</strong><small>{name.toLowerCase().replace(" ", ".")}@uls.edu</small></div><Status status={role} /></div>)}</section></div></Modal>}
    {usersOpen && <Modal title="Usuarios de la organización" onClose={() => setUsersOpen(false)} onSave={() => { setUsersOpen(false); notify("Usuarios asociados actualizados"); }} saveLabel="Guardar asociaciones"><div className="user-association"><div className="org-summary"><span className="org-avatar large">{current?.initials}</span><div><strong>{current?.name}</strong><p>{current?.email}</p></div><Button onClick={() => setAddUser(true)}><UserPlus /> Agregar usuario</Button></div>{[["María Rodríguez","Administrador"],["Juan Pérez","Editor"],["Carla Gómez","Lector"]].map(([name, role], i) => <label className="association-row" key={name}><input type="checkbox" defaultChecked={i < 2} /><span><strong>{name}</strong><small>{name.toLowerCase().replace(" ", ".")}@uls.edu</small></span><Status status={role} /></label>)}</div></Modal>}
    {addUser && <Modal title="Agregar usuario" onClose={() => setAddUser(false)} onSave={() => { setAddUser(false); notify("Usuario agregado a la organización"); }} saveLabel="Agregar usuario"><div className="form-grid"><label className="span-2">Correo institucional *<Input type="email" placeholder="nombre@userena.cl" /></label><label>Nombre completo *<Input placeholder="Nombre y apellidos" /></label><label>Rol *<select><option>Participante</option><option>Lector</option><option>Editor</option><option>Administrador</option></select></label><label className="span-2">Organización<Input value={current?.name ?? ""} disabled /></label></div></Modal>}
    {deactivate && <DeactivateOrganization current={current} selected={selected} setOrganizations={setOrganizations} onClose={() => setDeactivate(false)} notify={notify} />}
  </div>;
}

function Events({ events, setEvents, organizations, notify }: { events: PatoverEvent[]; setEvents: React.Dispatch<React.SetStateAction<PatoverEvent[]>>; organizations: Organization[]; notify: (message: string) => void }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("Todos"); const [orgFilter, setOrgFilter] = useState("Todas"); const [visibility, setVisibility] = useState("Todas"); const [wizard, setWizard] = useState(false); const [step, setStep] = useState(1); const [selected, setSelected] = useState<number | null>(null); const [action, setAction] = useState<string | null>(null);
  const filtered = events.filter(event => event.name.toLowerCase().includes(query.toLowerCase()) && (status === "Todos" || event.status === status) && (orgFilter === "Todas" || event.org === orgFilter) && (visibility === "Todas" || (visibility === "Pública" ? event.status === "Publicado" : event.status !== "Publicado"))); const current = selected === null ? undefined : events[selected];
  const transition = (next: EventStatus) => { if (selected === null) return; setEvents(prev => prev.map((event,i) => i === selected ? { ...event, status: next } : event)); setAction(null); notify(`Evento actualizado a ${next.toLowerCase()}`); };
  const createEvent = (form: HTMLFormElement) => { const data = new FormData(form); const next: PatoverEvent = { name: String(data.get("name") || "Nuevo evento ULS"), org: String(data.get("org") || organizations[0]?.name || "Universidad de La Serena"), date: "15 nov 2026", place: String(data.get("place") || "Por definir"), registered: 0, capacity: Number(data.get("capacity")) || 300, status: "Borrador" }; setEvents(prev => [...prev, next]); setWizard(false); notify("Evento creado como borrador"); };
  return <div className="page-stack"><div className="page-intro"><div><p className="eyebrow">MC-04</p><h2>Gestión de eventos</h2><p>Administra el ciclo de vida, configuración y publicación.</p></div><Button onClick={() => { setStep(1); setWizard(true); }}><Plus /> Crear evento</Button></div>
    <div className="summary-band"><div><strong>{events.length}</strong><span>Total</span></div><div><strong>{events.filter(e => e.status === "Publicado").length}</strong><span>Publicados</span></div><div><strong>{events.filter(e => e.status === "Configurado").length}</strong><span>Configurados</span></div><div><strong>{events.filter(e => e.status === "Borrador").length}</strong><span>Borradores</span></div></div>
    <section className="panel table-panel"><div className="toolbar event-toolbar"><div className="search-field"><Search /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar eventos..." /></div><select value={orgFilter} onChange={e => setOrgFilter(e.target.value)} aria-label="Filtrar por organización"><option>Todas</option>{organizations.map(o => <option key={o.initials}>{o.name}</option>)}</select><select value={status} onChange={e => setStatus(e.target.value)} aria-label="Filtrar por estado"><option>Todos</option><option>Publicado</option><option>Configurado</option><option>Borrador</option><option>Finalizado</option><option>Archivado</option></select><select value={visibility} onChange={e => setVisibility(e.target.value)} aria-label="Filtrar por visibilidad"><option>Todas</option><option>Pública</option><option>Restringida</option></select></div><div className="event-list">{filtered.length ? filtered.map(event => <EventCard key={event.name} event={event} onView={() => setSelected(events.indexOf(event))} onEdit={() => { setSelected(events.indexOf(event)); setAction("config"); }} />) : <EmptyState title="No se encontraron eventos" text="Ajusta la búsqueda o cambia el filtro de estado." />}</div><div className="table-footer"><span>Mostrando {filtered.length} de {events.length}</span><div><Button variant="outline" size="icon" disabled><ChevronLeft /></Button><Button variant="outline" size="icon" disabled><ChevronRight /></Button></div></div></section>
    {wizard && <EventWizard step={step} setStep={setStep} organizations={organizations} onClose={() => setWizard(false)} onCreate={createEvent} />}
    {current && selected !== null && <Modal wide title={current.name} onClose={() => { setSelected(null); setAction(null); }} onSave={() => { setSelected(null); setAction(null); }} saveLabel="Cerrar"><div className="event-detail"><div className="event-detail-head"><Status status={current.status} /><p>{current.org} · {current.date} · {current.place}</p></div><div className="detail-tabs"><Button variant={action !== "config" ? "default" : "ghost"} onClick={() => setAction(null)}>Información</Button><Button variant={action === "config" ? "default" : "ghost"} onClick={() => setAction("config")}>Configuración</Button></div>{action === "config" ? <EventConfiguration event={current} /> : <><div className="detail-facts"><div><span>Código</span><strong>EVT-2026-{String(selected + 1).padStart(3,"0")}</strong></div><div><span>Inscritos</span><strong>{current.registered} / {current.capacity}</strong></div><div><span>Organización</span><strong>{current.org}</strong></div><div><span>Ubicación</span><strong>{current.place}</strong></div></div><div className="quick-actions"><Button variant="outline" onClick={() => setAction("config")}><Settings2 /> Configurar</Button>{current.status === "Borrador" && <Button onClick={() => transition("Configurado")}><CheckCircle2 /> Completar configuración</Button>}{current.status === "Configurado" && <Button onClick={() => setAction("publish")}><Eye /> Publicar</Button>}{current.status === "Publicado" && <Button variant="outline" onClick={() => setAction("unpublish")}><EyeOff /> Despublicar</Button>}{current.status !== "Finalizado" && current.status !== "Archivado" && <Button variant="outline" onClick={() => setAction("finish")}><CheckCircle2 /> Finalizar</Button>}{current.status === "Finalizado" && <Button variant="outline" onClick={() => transition("Archivado")}><Archive /> Archivar</Button>}<Button variant="outline" onClick={() => setAction("duplicate")}><Copy /> Duplicar</Button></div></>}</div></Modal>}
    {current && action === "publish" && <EventActionModal mode="publish" event={current} onClose={() => setAction(null)} onConfirm={() => transition("Publicado")} />}
    {current && action === "unpublish" && <EventActionModal mode="unpublish" event={current} onClose={() => setAction(null)} onConfirm={() => transition("Configurado")} />}
    {current && action === "finish" && <EventActionModal mode="finish" event={current} onClose={() => setAction(null)} onConfirm={() => transition("Finalizado")} />}
    {current && action === "duplicate" && <EventActionModal mode="duplicate" event={current} onClose={() => setAction(null)} onConfirm={(name, keep) => { setEvents(prev => [...prev, { ...current, name: name || `${current.name} (copia)`, status: "Borrador", registered: 0, capacity: keep ? current.capacity : 300 }]); setAction(null); notify("Evento duplicado como borrador"); }} />}
  </div>;
}

function EventWizard({ step, setStep, organizations, onClose, onCreate }: { step: number; setStep: (step:number) => void; organizations: Organization[]; onClose: () => void; onCreate: (form: HTMLFormElement) => void }) {
  return <div className="modal-backdrop"><section className="modal modal-wide" role="dialog" aria-modal="true"><header><div><p className="eyebrow">MC-04 · RF-025</p><h2>Crear nuevo evento</h2></div><Button variant="ghost" size="icon" onClick={onClose} aria-label="Cerrar"><X /></Button></header><form onSubmit={e => { e.preventDefault(); if (step < 3) setStep(step + 1); else onCreate(e.currentTarget); }}><div className="modal-body"><div className="steps">{["Información", "Configuración", "Publicación"].map((label,i) => <div className={step >= i+1 ? "step active" : "step"} key={label}><span>{i+1}</span><small>{label}</small></div>)}</div>{step === 1 && <div className="form-grid"><label className="span-2">Nombre del evento *<Input name="name" required placeholder="Ej. Feria de Innovación 2026" /></label><label>Organización *<select name="org">{organizations.filter(o => o.status === "Activa").map(o => <option key={o.initials}>{o.name}</option>)}</select></label><label>Código *<Input required placeholder="EVT-2026-001" /></label><label>Fecha de inicio *<Input required type="date" /></label><label>Fecha de término *<Input required type="date" /></label><label className="span-2">Ubicación<Input name="place" placeholder="Campus o salón" /></label><label className="span-2">Descripción<textarea required placeholder="Describe el propósito del evento" /></label></div>}{step === 2 && <div className="option-list"><label className="config-input">Capacidad máxima<Input name="capacity" type="number" defaultValue="300" min="1" /></label><ToggleOption title="Inscripción habilitada" text="Permite que participantes se inscriban." active /><ToggleOption title="Acreditación" text="Activa la acreditación presencial." active /><ToggleOption title="Registro de asistencia" text="Registra asistencia general y por actividad." /><ToggleOption title="Visibilidad pública" text="Publica la ficha en el portal." /></div>}{step === 3 && <div className="review-box"><ShieldCheck /><h3>Información completa</h3><p>El evento se guardará como borrador para que puedas revisarlo antes de publicarlo.</p><dl><div><dt>Estado inicial</dt><dd>Borrador</dd></div><div><dt>Próximo paso</dt><dd>Revisar y publicar</dd></div></dl></div>}{step > 1 && <Button type="button" variant="ghost" onClick={() => setStep(step-1)}><ChevronLeft /> Volver</Button>}</div><footer><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button><Button type="submit">{step < 3 ? "Siguiente" : "Crear evento"}<ChevronRight /></Button></footer></form></section></div>;
}

function EventCard({ event, onView, onEdit }: { event: PatoverEvent; onView: () => void; onEdit: () => void }) { return <article className="event-card"><div className="event-date"><strong>{event.date.split(" ")[0]}</strong><span>{event.date.split(" ")[1]}</span></div><div className="event-main"><div><Status status={event.status} /><h3>{event.name}</h3><p>{event.org} · {event.place}</p></div><div className="capacity"><div><span>Inscritos</span><strong>{event.registered} / {event.capacity}</strong></div><div className="progress"><span style={{ width: `${event.registered/event.capacity*100}%` }} /></div></div></div><div className="event-actions"><Button variant="outline" size="icon" aria-label={`Ver ${event.name}`} onClick={onView}><Eye /></Button><Button variant="outline" size="icon" aria-label={`Configurar ${event.name}`} onClick={onEdit}><Settings2 /></Button></div></article>; }

function Reports({ events, notify }: { events: PatoverEvent[]; notify: (message: string) => void }) {
  const [period, setPeriod] = useState("Este mes"); const [event, setEvent] = useState("Todos los eventos"); const [advanced, setAdvanced] = useState(false); const [report, setReport] = useState<"dashboard" | "eventos" | "inscripciones" | "acreditacion" | "asistencia">("dashboard"); const [generated, setGenerated] = useState(false); const factor = period === "Este mes" ? 1 : period === "Últimos 3 meses" ? 2.4 : 4.8; const values = useMemo(() => [42,68,51,82,73,91,78].map(v => Math.min(98, v * (event === "Todos los eventos" ? 1 : .82))), [event]);
  const exportReport = () => { const rows = ["Evento,Organización,Inscritos,Acreditados,Asistentes", ...events.map(e => `"${e.name}","${e.org}",${e.registered},${Math.round(e.registered*.78)},${Math.round(e.registered*.68)}`)]; const url = URL.createObjectURL(new Blob([rows.join("\n")], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "reporte-patover.csv"; anchor.click(); URL.revokeObjectURL(url); notify("Reporte CSV exportado correctamente"); };
  if (report !== "dashboard") return <ReportSection type={report} events={events} generated={generated} setGenerated={setGenerated} onBack={() => { setReport("dashboard"); setGenerated(false); }} onExport={exportReport} />;
  return <div className="page-stack"><div className="page-intro"><div><p className="eyebrow">MC-10</p><h2>Reportes y dashboards</h2><p>Analiza inscripciones, acreditación y asistencia dentro de tu ámbito autorizado.</p></div><Button onClick={exportReport}><Download /> Exportar reporte</Button></div>
    <section className="filters"><label>Período<select value={period} onChange={e => setPeriod(e.target.value)}><option>Este mes</option><option>Últimos 3 meses</option><option>Este año</option></select></label><label>Evento<select value={event} onChange={e => setEvent(e.target.value)}><option>Todos los eventos</option>{events.map(e => <option key={e.name}>{e.name}</option>)}</select></label><Button variant="outline" onClick={() => setAdvanced(!advanced)}><Settings2 /> {advanced ? "Ocultar filtros" : "Más filtros"}</Button><span>Actualizado hace 5 min</span></section>
    {advanced && <section className="advanced-filters"><label>Organización<select><option>Todas</option><option>Facultad de Ingeniería</option><option>Dirección de Vinculación</option></select></label><label>Estado<select><option>Todos</option><option>Publicado</option><option>Finalizado</option></select></label><label className="check-row"><input type="checkbox" /> Participantes</label><label className="check-row"><input type="checkbox" /> Acreditación</label><label className="check-row"><input type="checkbox" /> Asistencia</label><Button variant="outline" onClick={() => { setPeriod("Este mes"); setEvent("Todos los eventos"); }}>Limpiar filtros</Button></section>}
    <div className="metric-grid report-metrics"><Metric label="Inscripciones" value={Math.round(1284*factor).toLocaleString("es-CL")} note="+18% vs período anterior" icon={<Users />} /><Metric label="Acreditados" value={Math.round(962*factor).toLocaleString("es-CL")} note="74,9% de inscritos" icon={<ShieldCheck />} /><Metric label="Asistencias" value={Math.round(874*factor).toLocaleString("es-CL")} note="90,8% de acreditados" icon={<CalendarDays />} /><Metric label="Tasa de asistencia" value="78%" note="Sobre acreditados" icon={<FileBarChart />} /></div>
    <div className="report-grid"><section className="panel"><div className="section-title"><div><p className="eyebrow">Participación por actividad</p><h3>Inscripciones y asistencia</h3></div><span className="legend"><i /> Inscripciones <i /> Asistencia</span></div><div className="large-chart">{values.map((v,i) => <div key={i}><div className="bars"><span style={{height:`${v}%`}}/><span style={{height:`${v*.76}%`}}/></div><small>Sem {i+1}</small></div>)}</div></section><section className="panel"><div className="section-title"><div><p className="eyebrow">Conversión</p><h3>Estado de participación</h3></div></div><div className="funnel"><div><strong>1.284</strong><span>Inscritos</span></div><div><strong>962</strong><span>Acreditados</span></div><div><strong>874</strong><span>Asistentes</span></div></div><p className="formula">Indicador calculado sobre registros válidos y activos.</p></section></div>
    <section className="panel"><div className="section-title"><div><p className="eyebrow">Reportes disponibles</p><h3>Selecciona una sección</h3></div></div><div className="report-selector"><Button variant="outline" onClick={() => setReport("eventos")}><CalendarDays /> Reporte de eventos</Button><Button variant="outline" onClick={() => setReport("inscripciones")}><Users /> Inscripciones</Button><Button variant="outline" onClick={() => setReport("acreditacion")}><ShieldCheck /> Acreditación</Button><Button variant="outline" onClick={() => setReport("asistencia")}><CheckCircle2 /> Asistencia</Button></div></section>
  </div>;
}

function ToggleOption({ title, text, active = false }: { title: string; text: string; active?: boolean }) { const [on,setOn] = useState(active); return <div className="toggle-option"><div><strong>{title}</strong><p>{text}</p></div><Button type="button" variant="ghost" className={`switch ${on ? "on" : ""}`} onClick={() => setOn(!on)} aria-label={`${on ? "Desactivar" : "Activar"} ${title}`}><span /></Button></div>; }
function EventConfiguration({ event }: { event: PatoverEvent }) { return <div className="configuration-stack"><section className="config-section"><ToggleOption title="Habilitar período de inscripción" text="Permite inscripciones entre las fechas indicadas." active /><div className="form-grid compact-form"><label>Inicio<Input type="date" defaultValue="2026-09-01" /></label><label>Finalización<Input type="date" defaultValue="2026-09-23" /></label></div></section><section className="config-section"><ToggleOption title="Limitar capacidad" text={`Capacidad actual: ${event.capacity} participantes.`} active /><label className="config-input">Número máximo<Input type="number" defaultValue={event.capacity} /></label></section><section className="config-section"><h3>Datos de inscripción</h3>{["Nombre completo","Correo electrónico","Teléfono","Otro dato no personal"].map((label,i) => <label className="check-row" key={label}><input type="checkbox" defaultChecked={i < 3} /> {label}</label>)}<label>Finalidad de teléfono y correo<textarea defaultValue="Enviar confirmaciones y avisos operativos del evento." /></label></section><section className="config-section"><ToggleOption title="Requiere aprobación" text="La inscripción deberá ser revisada antes de acreditarse." /><label>Tipo de acreditación<select><option>Presencial con código QR</option><option>Validación manual</option></select></label><label>Condiciones<textarea placeholder="Indica las condiciones de aprobación" /></label></section><section className="config-section"><h3>Tipo de asistencia</h3><select defaultValue="Ambos"><option>Evento</option><option>Actividad</option><option>Ambos</option></select><h3>Visibilidad</h3><select defaultValue={event.status === "Publicado" ? "Pública" : "Restringida"}><option>Pública</option><option>Restringida</option></select></section></div>; }
function EventActionModal({ mode, event, onClose, onConfirm }: { mode: "publish"|"unpublish"|"finish"|"duplicate"; event:PatoverEvent; onClose:()=>void; onConfirm:(name?:string, keep?:boolean)=>void }) { const [name,setName]=useState(`${event.name} (copia)`); const [keep,setKeep]=useState(true); const copy=mode==="duplicate"; const title={publish:"Publicar evento",unpublish:"Despublicar evento",finish:"Finalizar evento",duplicate:"Duplicar evento"}[mode]; return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">MC-04</p><h2>{title}</h2></div><Button variant="ghost" size="icon" onClick={onClose}><X /></Button></header><div className="modal-body action-body">{mode==="publish" && <><div className="requirements"><CheckCircle2 /><div><strong>Información general</strong><span>Completa</span></div><CheckCircle2 /><div><strong>Fechas y ubicación</strong><span>Completas</span></div><CheckCircle2 /><div><strong>Configuración e inscripción</strong><span>Completas</span></div></div><div className="inline-alert"><ShieldCheck /><span>Estado actual: {event.status}. Al publicar será visible para participantes.</span></div></>}{mode==="unpublish" && <><div className="inline-alert warning"><AlertTriangle /><span>El evento dejará de ser visible y no aceptará nuevas inscripciones.</span></div><label>Motivo de despublicación<textarea placeholder="Describe el motivo" /></label></>}{mode==="finish" && <div className="confirm-copy"><CheckCircle2 /><h3>¿Confirmas la finalización?</h3><p>Se cerrarán las inscripciones y la asistencia quedará disponible para reportes.</p></div>}{copy && <div className="form-grid"><label className="span-2">Nuevo nombre<Input value={name} onChange={e=>setName(e.target.value)} /></label><label className="span-2 check-row"><input type="checkbox" checked={keep} onChange={e=>setKeep(e.target.checked)} /> Mantener la misma configuración</label></div>}</div><footer><Button variant="outline" onClick={onClose}>Volver</Button><Button onClick={()=>onConfirm(name,keep)}>{copy?"Duplicar":"Confirmar"}</Button></footer></section></div>; }
function DeactivateOrganization({ current, selected, setOrganizations, onClose, notify }: { current?:Organization; selected:number; setOrganizations:React.Dispatch<React.SetStateAction<Organization[]>>; onClose:()=>void; notify:(m:string)=>void }) { const activating=current?.status==="Inactiva"; return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">MC-03</p><h2>{activating?"Activar organización":"Desactivar organización"}</h2></div><Button variant="ghost" size="icon" onClick={onClose}><X /></Button></header><div className="modal-body action-body">{!activating && <div className="inline-alert warning"><AlertTriangle /><span>La organización dejará de estar disponible para crear eventos nuevos. Sus registros históricos se conservarán.</span></div>}<label>Motivo (opcional)<textarea placeholder="Escribe el motivo del cambio de estado" /></label></div><footer><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={()=>{setOrganizations(prev=>prev.map((o,i)=>i===selected?{...o,status:activating?"Activa":"Inactiva"}:o));onClose();notify("Estado de la organización actualizado");}}>{activating?"Activar":"Desactivar"}</Button></footer></section></div>; }
function ReportSection({ type, events, generated, setGenerated, onBack, onExport }: { type:"eventos"|"inscripciones"|"acreditacion"|"asistencia"; events:PatoverEvent[]; generated:boolean; setGenerated:(v:boolean)=>void; onBack:()=>void; onExport:()=>void }) { const labels={eventos:"Reporte de eventos",inscripciones:"Reporte de inscripciones",acreditacion:"Reporte de acreditación",asistencia:"Reporte de asistencia"}; return <div className="page-stack"><div className="page-intro"><div><Button variant="ghost" onClick={onBack}><ChevronLeft /> Volver a reportes</Button><p className="eyebrow">MC-10</p><h2>{labels[type]}</h2><p>Configura los filtros y genera el detalle correspondiente.</p></div>{generated&&<Button onClick={onExport}><Download /> Exportar</Button>}</div><section className="filters report-filters"><label>Evento<select><option>Todos los eventos</option>{events.map(e=><option key={e.name}>{e.name}</option>)}</select></label>{type==="eventos"?<><label>Período<select><option>Mes</option><option>Año</option><option>Día</option></select></label><label>Organización<select><option>Todas</option><option>Facultad de Ingeniería</option></select></label></>:<><label>Estado<select><option>Todos</option><option>Confirmado</option><option>Pendiente</option></select></label><label>Fecha inicio<Input type="date" /></label><label>Fecha final<Input type="date" /></label></>}<Button onClick={()=>setGenerated(true)}><FileBarChart /> Generar reporte</Button></section>{generated?<section className="panel table-panel"><div className="section-title report-table-title"><div><p className="eyebrow">Resultados</p><h3>{labels[type]}</h3></div></div><div className="table-wrap"><table><thead><tr>{type==="eventos"?<><th>Evento</th><th>Fecha</th><th>Estado</th><th>Inscritos</th><th>Acreditados</th><th>Asistentes</th></>:<><th>N°</th><th>Nombre</th><th>Evento</th><th>Fecha</th><th>Estado</th></>}</tr></thead><tbody>{type==="eventos"?events.map(e=><tr key={e.name}><td><strong>{e.name}</strong><small>{e.org}</small></td><td>{e.date}</td><td><Status status={e.status}/></td><td>{e.registered}</td><td>{Math.round(e.registered*.78)}</td><td>{Math.round(e.registered*.68)}</td></tr>):["Ana Torres","Benjamín Silva","Catalina Rojas","Diego Morales"].map((name,i)=><tr key={name}><td>{i+1}</td><td><strong>{name}</strong></td><td>{events[i%events.length]?.name}</td><td>{type==="inscripciones"?"18 sep 2026":"24 sep 2026"}</td><td><Status status={i===2?"Pendiente":"Confirmado"}/></td></tr>)}</tbody></table></div></section>:<EmptyState title="Genera el reporte" text="Selecciona los filtros y presiona Generar reporte para ver los resultados."/>}</div>; }
function Status({ status }: { status: string }) { return <span className={`status status-${status.toLowerCase()}`}>{status}</span>; }
function EventRow({ event }: { event: PatoverEvent }) { return <div className="event-row"><div className="event-date small"><strong>{event.date.split(" ")[0]}</strong><span>{event.date.split(" ")[1]}</span></div><div><strong>{event.name}</strong><span>{event.org}</span></div><Status status={event.status} /></div>; }
function EmptyState({ title, text }: { title:string; text:string }) { return <div className="empty-state"><div><Search /></div><strong>{title}</strong><p>{text}</p></div>; }
function Modal({ title, children, onClose, onSave, saveLabel="Guardar cambios", wide=false }: { title:string; children:React.ReactNode; onClose:()=>void; onSave:()=>void; saveLabel?:string; wide?:boolean }) { return <div className="modal-backdrop" role="presentation" onMouseDown={e => { if(e.currentTarget === e.target) onClose(); }}><section className={`modal ${wide ? "modal-wide" : ""}`} role="dialog" aria-modal="true"><header><div><p className="eyebrow">PATOVER</p><h2>{title}</h2></div><Button variant="ghost" size="icon" onClick={onClose} aria-label="Cerrar"><X /></Button></header><div className="modal-body">{children}</div><footer><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={onSave}>{saveLabel}</Button></footer></section></div>; }
function ConfirmModal({ title, warning, onClose, onConfirm }: { title:string; warning:boolean; onClose:()=>void; onConfirm:()=>void }) { return <div className="modal-backdrop"><section className="modal confirm-modal" role="dialog" aria-modal="true"><div className={`confirm-icon ${warning ? "danger" : ""}`}>{warning ? <AlertTriangle /> : <Archive />}</div><h2>{warning ? "No es posible desactivar" : title}</h2><p>{warning ? "La organización tiene eventos activos asociados. Debes finalizarlos o reasignarlos antes de desactivarla." : "Esta acción cambiará el estado de la organización. Puedes revertirla más adelante."}</p><div className="confirm-actions"><Button variant="outline" onClick={onClose}>{warning ? "Entendido" : "Cancelar"}</Button>{!warning && <Button onClick={onConfirm}>Confirmar</Button>}</div></section></div>; }
function Profile({ account, setAccount, notify }: { account: Account; setAccount: (a: Account) => void; notify: (m: string) => void }) {
  const [name, setName] = useState(account.name);
  const [email, setEmail] = useState(account.email);
  const [current, setCurrent] = useState("");
  const [next, setNext] = useState("");
  const [confirm, setConfirm] = useState("");
  const [show, setShow] = useState(false);
  const [dataError, setDataError] = useState("");
  const [passError, setPassError] = useState("");
  const initialsOf = (value: string) => value.trim().split(/\s+/).slice(0, 2).map(p => p[0]?.toUpperCase() ?? "").join("") || "US";

  const saveData = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!name.trim()) { setDataError("Escribe tu nombre completo."); return; }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) { setDataError("Ingresa un correo válido."); return; }
    setDataError("");
    setAccount({ ...account, name: name.trim(), email: email.trim().toLowerCase(), initials: initialsOf(name) });
    notify("Datos de cuenta actualizados");
  };

  const savePassword = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (current !== account.password) { setPassError("La contraseña actual no coincide."); return; }
    if (next.length < 8) { setPassError("La nueva contraseña debe tener al menos 8 caracteres."); return; }
    if (next !== confirm) { setPassError("La confirmación no coincide con la nueva contraseña."); return; }
    setPassError("");
    setAccount({ ...account, password: next });
    setCurrent(""); setNext(""); setConfirm("");
    notify("Contraseña actualizada");
  };

  return <div className="page-stack">
    <div className="page-intro"><div><p className="eyebrow">Cuenta</p><h2>Mi perfil</h2><p>Actualiza tus datos de acceso. Las nuevas credenciales se usarán al volver a iniciar sesión.</p></div></div>
    <section className="panel profile-head"><div className="avatar large">{account.initials}</div><div><strong>{account.name}</strong><p>{account.role}</p><p>{account.email}</p></div></section>
    <div className="profile-grid">
      <section className="panel"><form className="profile-form" onSubmit={saveData}>
        <div className="section-title"><div><p className="eyebrow">Datos personales</p><h3>Nombre y correo</h3></div></div>
        <label>Nombre completo<Input value={name} onChange={e => { setName(e.target.value); setDataError(""); }} /></label>
        <label>Correo de acceso<Input type="email" value={email} onChange={e => { setEmail(e.target.value); setDataError(""); }} /></label>
        {dataError && <div className="inline-alert danger"><AlertTriangle /><span>{dataError}</span></div>}
        <div className="profile-actions"><Button type="submit">Guardar cambios</Button><Button type="button" variant="outline" onClick={() => { setName(account.name); setEmail(account.email); setDataError(""); }}>Restablecer</Button></div>
      </form></section>
      <section className="panel"><form className="profile-form" onSubmit={savePassword}>
        <div className="section-title"><div><p className="eyebrow">Seguridad</p><h3>Cambiar contraseña</h3></div><Button type="button" variant="ghost" size="icon" onClick={() => setShow(!show)} aria-label={show ? "Ocultar contraseñas" : "Mostrar contraseñas"}>{show ? <EyeOff /> : <Eye />}</Button></div>
        <label>Contraseña actual<Input type={show ? "text" : "password"} value={current} onChange={e => { setCurrent(e.target.value); setPassError(""); }} /></label>
        <label>Nueva contraseña<Input type={show ? "text" : "password"} value={next} onChange={e => { setNext(e.target.value); setPassError(""); }} /></label>
        <label>Confirmar nueva contraseña<Input type={show ? "text" : "password"} value={confirm} onChange={e => { setConfirm(e.target.value); setPassError(""); }} /></label>
        {passError && <div className="inline-alert danger"><AlertTriangle /><span>{passError}</span></div>}
        <p className="demo-note">Usa al menos 8 caracteres.</p>
        <div className="profile-actions"><Button type="submit">Actualizar contraseña</Button></div>
      </form></section>
    </div>
  </div>;
}
